import { ScriptPrompt } from '@/types';

export const RECORDING_SCRIPT: ScriptPrompt[] = [
  // === Section A: Common Words & Phrases ===
  { id: 'ScriptA_1', type: 'scripted', text: 'Maakye', meaning: 'Good morning' },
  { id: 'ScriptA_2', type: 'scripted', text: 'Maaha', meaning: 'Good afternoon' },
  { id: 'ScriptA_3', type: 'scripted', text: 'Maadwo', meaning: 'Good evening/night' },
  { id: 'ScriptA_4', type: 'scripted', text: 'Wo ho te sɛn?', meaning: 'How are you?' },
  { id: 'ScriptA_5', type: 'scripted', text: 'Me ho yɛ.', meaning: 'I am fine.' },
  { id: 'ScriptA_6', type: 'scripted', text: 'Bɔkɔɔ.', meaning: 'Fine / Cool / Okay.' },
  { id: 'ScriptA_7', type: 'scripted', text: 'Yɛda w’ase.', meaning: 'Thank you.' },
  { id: 'ScriptA_8', type: 'scripted', text: 'Medaase paa.', meaning: 'Thank you very much.' },
  { id: 'ScriptA_9', type: 'scripted', text: 'Yɛ frɛ wo sɛn?', meaning: 'What are you called?' },
  { id: 'ScriptA_10', type: 'scripted', text: 'Wo din de sɛn?', meaning: 'What is your name?' },
  { id: 'ScriptA_11', type: 'scripted', text: 'Me din de [Participant\'s First Name].', meaning: 'My name is [Participant\'s First Name].' },
  { id: 'ScriptA_12', type: 'scripted', text: 'Bra ha.', meaning: 'Come here.' },
  { id: 'ScriptA_13', type: 'scripted', text: 'Kɔ hɔ.', meaning: 'Go there.' },
  { id: 'ScriptA_14', type: 'scripted', text: 'Kɔ w’anim.', meaning: 'Go forward.' },
  { id: 'ScriptA_15', type: 'scripted', text: 'San w’akyi.', meaning: 'Go back.' },
  { id: 'ScriptA_16', type: 'scripted', text: 'Tena ase.', meaning: 'Sit down.' },
  { id: 'ScriptA_17', type: 'scripted', text: 'Gyina hɔ.', meaning: 'Stand there.' },
  { id: 'ScriptA_18', type: 'scripted', text: 'Sɔre gyina hɔ.', meaning: 'Stand up.' },
  { id: 'ScriptA_19', type: 'scripted', text: 'Fa kyɛ me.', meaning: 'Forgive me.' },
  { id: 'ScriptA_20', type: 'scripted', text: 'Fa ma me.', meaning: 'Give it to me.' },
  { id: 'ScriptA_21', type: 'scripted', text: 'Ɛyɛ.', meaning: 'It is good / Okay.' },
  { id: 'ScriptA_22', type: 'scripted', text: 'Ɛnyɛ.', meaning: 'It is not good.' },
  { id: 'ScriptA_23', type: 'scripted', text: 'Ɛnteɛ.', meaning: 'It is not right/true.' },
  { id: 'ScriptA_24', type: 'scripted', text: 'Boa me!', meaning: 'Help me!' },
  { id: 'ScriptA_25', type: 'scripted', text: 'Me pa wo kyɛw.', meaning: 'Please / Excuse me.' },
  { id: 'ScriptA_26', type: 'scripted', text: 'Kafra.', meaning: 'Sorry / Excuse me.' },
  { id: 'ScriptA_27', type: 'scripted', text: 'Mesrɛ wo.', meaning: 'Please / I beg you.' },
  { id: 'ScriptA_28', type: 'scripted', text: 'Mesrɛ wo, tie me.', meaning: 'Please, listen to me.' },
  { id: 'ScriptA_29', type: 'scripted', text: 'Me pa wo kyɛw fakyɛ me.', meaning: 'Please forgive me.' },
  { id: 'ScriptA_30', type: 'scripted', text: 'Me honam yɛ me ya.', meaning: 'My body hurts / I feel sick.' },
  { id: 'ScriptA_31', type: 'scripted', text: 'Frɛ me dɔkita no.', meaning: 'Call the doctor for me.' },
  { id: 'ScriptA_32', type: 'scripted', text: 'Me werɛ afi.', meaning: 'I have forgotten.' },
  { id: 'ScriptA_33', type: 'scripted', text: 'Menhuu no.', meaning: 'I didn\'t see it/him/her.' },
  { id: 'ScriptA_34', type: 'scripted', text: 'Mente aseɛ.', meaning: 'I don\'t understand.' },
  { id: 'ScriptA_35', type: 'scripted', text: 'Me te aseɛ.', meaning: 'I understand.' },
  { id: 'ScriptA_36', type: 'scripted', text: 'Kasa brɛoo.', meaning: 'Speak slowly.' },
  { id: 'ScriptA_37', type: 'scripted', text: 'Kasa den.', meaning: 'Speak loudly / firmly.' },
  { id: 'ScriptA_38', type: 'scripted', text: 'Adɛn nti na woreyɛ saa?', meaning: 'Why are you doing that?' },
  { id: 'ScriptA_39', type: 'scripted', text: 'Ɛhe na ɔwɔ?', meaning: 'Where is he/she?' },
  { id: 'ScriptA_40', type: 'scripted', text: 'Wobɛtumi aboa me anaa?', meaning: 'Can you help me?' },

  // === Section B: Numbers, Dates, and Time ===
  { id: 'ScriptB_1', type: 'scripted', text: 'Hwee', meaning: 'Zero / Nothing' },
  { id: 'ScriptB_2', type: 'scripted', text: 'Baako', meaning: 'One' },
  { id: 'ScriptB_3', type: 'scripted', text: 'Mmienu', meaning: 'Two' },
  { id: 'ScriptB_4', type: 'scripted', text: 'Mmiɛnsa', meaning: 'Three' },
  { id: 'ScriptB_5', type: 'scripted', text: 'Enan', meaning: 'Four' },
  { id: 'ScriptB_6', type: 'scripted', text: 'Enum', meaning: 'Five' },
  { id: 'ScriptB_7', type: 'scripted', text: 'Nsia', meaning: 'Six' },
  { id: 'ScriptB_8', type: 'scripted', text: 'Nson', meaning: 'Seven' },
  { id: 'ScriptB_9', type: 'scripted', text: 'Nwɔtwe', meaning: 'Eight' },
  { id: 'ScriptB_10', type: 'scripted', text: 'Nkron', meaning: 'Nine' },
  { id: 'ScriptB_11', type: 'scripted', text: 'Edu', meaning: 'Ten' },
  { id: 'ScriptB_12', type: 'scripted', text: 'Du baako', meaning: 'Eleven' },
  { id: 'ScriptB_13', type: 'scripted', text: 'Du mmienu', meaning: 'Twelve' },
  { id: 'ScriptB_14', type: 'scripted', text: 'Du mmiɛnsa', meaning: 'Thirteen' },
  { id: 'ScriptB_15', type: 'scripted', text: 'Aduonu', meaning: 'Twenty' },
  { id: 'ScriptB_16', type: 'scripted', text: 'Aduonu baako', meaning: 'Twenty-one' },
  { id: 'ScriptB_17', type: 'scripted', text: 'Aduasa', meaning: 'Thirty' },
  { id: 'ScriptB_18', type: 'scripted', text: 'Aduanan', meaning: 'Forty' },
  { id: 'ScriptB_19', type: 'scripted', text: 'Aduonum', meaning: 'Fifty' },
  { id: 'ScriptB_20', type: 'scripted', text: 'Aduosia', meaning: 'Sixty' },
  { id: 'ScriptB_21', type: 'scripted', text: 'Aduɔson', meaning: 'Seventy' },
  { id: 'ScriptB_22', type: 'scripted', text: 'Aduɔwɔtwe', meaning: 'Eighty' },
  { id: 'ScriptB_23', type: 'scripted', text: 'Aduɔkron', meaning: 'Ninety' },
  { id: 'ScriptB_24', type: 'scripted', text: 'Ɔha', meaning: 'One hundred' },
  { id: 'ScriptB_25', type: 'scripted', text: 'Apem', meaning: 'One thousand' },
  { id: 'ScriptB_26', type: 'scripted', text: 'Ɔpepem', meaning: 'One million' },
  { id: 'ScriptB_27', type: 'scripted', text: 'Ɛyɛ dɔnhwere mmienu.', meaning: 'It is two o\'clock.' },
  { id: 'ScriptB_28', type: 'scripted', text: 'Meda nnɔnkron.', meaning: 'I sleep at nine o\'clock.' }, // Or "I sleep for nine hours." - context dependent, assuming time.
  { id: 'ScriptB_29', type: 'scripted', text: 'Ɛnnɛ yɛ Benada.', meaning: 'Today is Tuesday.' },
  { id: 'ScriptB_30', type: 'scripted', text: 'Ɛdwoada', meaning: 'Monday' },
  { id: 'ScriptB_31', type: 'scripted', text: 'Ɛbenada', meaning: 'Tuesday' },
  { id: 'ScriptB_32', type: 'scripted', text: 'Wukuada', meaning: 'Wednesday' },
  { id: 'ScriptB_33', type: 'scripted', text: 'Yawda', meaning: 'Thursday' },
  { id: 'ScriptB_34', type: 'scripted', text: 'Fiada', meaning: 'Friday' },
  { id: 'ScriptB_35', type: 'scripted', text: 'Memeneda', meaning: 'Saturday' },
  { id: 'ScriptB_36', type: 'scripted', text: 'Kwasiada', meaning: 'Sunday' },
  { id: 'ScriptB_37', type: 'scripted', text: 'Ɛbɔ', meaning: 'January / September' }, // Specify context if needed, or use more specific month names if available
  { id: 'ScriptB_38', type: 'scripted', text: 'Ɔpɛpɔn', meaning: 'February' },
  { id: 'ScriptB_39', type: 'scripted', text: 'Ɔbɛnem', meaning: 'March' },
  { id: 'ScriptB_40', type: 'scripted', text: 'Oforisuo', meaning: 'April' },
  { id: 'ScriptB_41', type: 'scripted', text: 'Kotonimma', meaning: 'May' },
  { id: 'ScriptB_42', type: 'scripted', text: 'Ayɛwohomumɔ', meaning: 'June' },
  { id: 'ScriptB_43', type: 'scripted', text: 'Kitawonsa', meaning: 'July' },
  { id: 'ScriptB_44', type: 'scripted', text: 'Ɔsanaa', meaning: 'August' },
  { id: 'ScriptB_45', type: 'scripted', text: 'Ɛbɔ', meaning: 'September / January' }, // Specify context if needed
  { id: 'ScriptB_46', type: 'scripted', text: 'Ahinime', meaning: 'October' },
  { id: 'ScriptB_47', type: 'scripted', text: 'Obubuo', meaning: 'November' },
  { id: 'ScriptB_48', type: 'scripted', text: 'Ɔpɛnimma', meaning: 'December' },
  { id: 'ScriptB_49', type: 'scripted', text: 'Wei yɛ sɛn?', meaning: 'How much is this?' },
  { id: 'ScriptB_50', type: 'scripted', text: 'Ɛyɛ Ghana Cedis aduonum.', meaning: 'It is fifty Ghana Cedis.' },
  { id: 'ScriptB_51', type: 'scripted', text: 'Mɛtua sidi ɔha ne aduasa enum.', meaning: 'I will pay one hundred and thirty-five cedis.' },

  // === Section C: Everyday Situations ===
  // Market/Shopping
  { id: 'ScriptC_1', type: 'scripted', text: 'Mepaakyɛw, ntoosi no boɔ yɛ sɛn?', meaning: 'Please, how much are the tomatoes?' },
  { id: 'ScriptC_2', type: 'scripted', text: 'Mepaakyɛw, bankye no boɔ yɛ sɛn?', meaning: 'Please, how much is the cassava?' },
  { id: 'ScriptC_3', type: 'scripted', text: 'Twa so ma me kakra.', meaning: 'Reduce the price a little for me.' },
  { id: 'ScriptC_4', type: 'scripted', text: 'Kɔnkontire mmiɛnsa bɛyɛ sɛn?', meaning: 'How much will three plantains be?' },
  { id: 'ScriptC_5', type: 'scripted', text: 'Ma me kilo mmienu.', meaning: 'Give me two kilos.' },
  { id: 'ScriptC_6', type: 'scripted', text: 'Menya nkateɛ nwononwono no bi anaa?', meaning: 'Can I get some of the roasted groundnuts?' },
  { id: 'ScriptC_7', type: 'scripted', text: 'Merepɛ ankaa twɔ.', meaning: 'I am looking for oranges to buy.' },
  { id: 'ScriptC_8', type: 'scripted', text: 'Fa nkyene paketɛ baako ma me.', meaning: 'Give me one packet of salt.' },

  // Food/Restaurant
  { id: 'ScriptC_9', type: 'scripted', text: 'Mepaakyɛw, fa aduane no brɛ me.', meaning: 'Please, bring me the food.' },
  { id: 'ScriptC_10', type: 'scripted', text: 'Aduane bɛn na wowɔ nnɛ?', meaning: 'What food do you have today?' },
  { id: 'ScriptC_11', type: 'scripted', text: 'Me pɛ fufuo ne nkrakra ɛtɔ.', meaning: 'I want fufu with light soup.' }, // Nkrakra = light soup, ɛtɔ = soup/stew
  { id: 'ScriptC_12', type: 'scripted', text: 'Nsuo no yɛ nwunu dodo.', meaning: 'The water is too cold.' },
  { id: 'ScriptC_13', type: 'scripted', text: 'Fa mako ma me kakra.', meaning: 'Give me a little pepper.' },
  { id: 'ScriptC_14', type: 'scripted', text: 'Yetumi di saa aduane yi wɔ ha?', meaning: 'Can we eat this food here?' },
  { id: 'ScriptC_15', type: 'scripted', text: 'Wobɛtumi akyekyere deɛ aka no ama me?', meaning: 'Can you pack the leftovers for me?' },

  // Health/Hospital
  { id: 'ScriptC_16', type: 'scripted', text: 'Me ho mfa me.', meaning: 'I am not feeling well.' },
  { id: 'ScriptC_17', type: 'scripted', text: 'Meyam yɛ me ya.', meaning: 'My stomach hurts.' },
  { id: 'ScriptC_18', type: 'scripted', text: 'Me tipae yɛ me ya.', meaning: 'My head hurts / I have a headache.' },
  { id: 'ScriptC_19', type: 'scripted', text: 'Meyam keka me efiri nnora.', meaning: 'My stomach has been hurting since yesterday.' },
  { id: 'ScriptC_20', type: 'scripted', text: 'Ɛhe na yɛ nya nnuro tɔ?', meaning: 'Where can we buy medicine?' },
  { id: 'ScriptC_21', type: 'scripted', text: 'Me hia dɔkota ntɛm ara!', meaning: 'I need a doctor immediately!' },
  { id: 'ScriptC_22', type: 'scripted', text: 'Me nan asi me yafunu mu.', meaning: 'I have diarrhoea / stomach upset.' }, // Literal: My leg has stepped in my stomach

  // Work/Office
  { id: 'ScriptC_23', type: 'scripted', text: 'M’aba adwuma.', meaning: 'I have come to work.' },
  { id: 'ScriptC_24', type: 'scripted', text: 'Mereyɛ meeting.', meaning: 'I am having a meeting.' },
  { id: 'ScriptC_25', type: 'scripted', text: 'Yɛwɔ nhyiamu nnɔn mmienu awia.', meaning: 'We have a meeting at 2 PM.' },
  { id: 'ScriptC_26', type: 'scripted', text: 'Mɛtumi de kɔmputa yi ayɛ m\'adwuma?', meaning: 'Can I use this computer to do my work?' },
  { id: 'ScriptC_27', type: 'scripted', text: 'Mesrɛ wo, print krataa yi ma me.', meaning: 'Please, print this paper for me.' },
  { id: 'ScriptC_28', type: 'scripted', text: 'Mɛkɔ akɔdi m\'adwuma awia aduane.', meaning: 'I am going to eat my lunch at work.' }, // Or "I will go eat my work lunch"

  // Travel/Transport
  { id: 'ScriptC_29', type: 'scripted', text: 'Kar bɛn na ɛkɔ Nkran?', meaning: 'Which car/bus goes to Accra?' },
  { id: 'ScriptC_30', type: 'scripted', text: 'Gyina ma me wɔ beaeɛ a ɛbɛn hɔ no.', meaning: 'Stop for me at the place nearby.' },
  { id: 'ScriptC_31', type: 'scripted', text: 'M\'ani agye m\'akwantu yi ho.', meaning: 'I enjoyed this journey.' },
  { id: 'ScriptC_32', type: 'scripted', text: 'Trotro sika no yɛ sɛn?', meaning: 'How much is the Trotro fare?' },
  { id: 'ScriptC_33', type: 'scripted', text: 'Yɛadu?', meaning: 'Have we arrived?' },
  { id: 'ScriptC_34', type: 'scripted', text: 'Yɛbɛn?', meaning: 'Are we close?' },

  // === Section D: Spontaneous Speech (Prompts) ===
  // Meanings are already included in the 'text' field for spontaneous prompts
  { id: 'Spontaneous_1', type: 'spontaneous', text: 'Introduce Yourself – Name, age, where you live, what you do. (Mesrɛ wo, ka wo ho asɛm kyerɛ me. Wo din, w’adi mfeɛ sɛn, ɛhe na wote, adwuma bɛn na woyɛ, anaa sukuu bɛn na wokɔ?)' },
  { id: 'Spontaneous_2', type: 'spontaneous', text: 'Daily Routine – How you start and end your day. (Kyerɛkyerɛ me sɛnea wo da bɔbɔɔso kɔpem sɛ ɛkɔwie. Dɛn na woyɛ anɔpa, awia, ne anadwo?)' },
  { id: 'Spontaneous_3', type: 'spontaneous', text: 'Describe Your Environment – Talk about what you see around you right now. (Kasa fa nnoɔma a ɛwɔ baabi a wote seesei yi ho.)' },
  { id: 'Spontaneous_4', type: 'spontaneous', text: 'Narrate a Past Event – Describe something interesting that happened to you recently. (Ka asɛm bi a ɛsi nnansa yi ara a ɛyɛ anigye anaasɛ ɛyɛ nwanwa ho asɛm kyerɛ me.)' },
  { id: 'Spontaneous_5', type: 'spontaneous', text: 'Favorite Food – Talk about your favorite Twi food. Why do you like it? How is it prepared? (Kasa fa Twi aduane a wopɛ pa ara ho. Adɛn nti na wopɛ saa aduane no? Sɛn na yɛnoa?)' },
  { id: 'Spontaneous_6', type: 'spontaneous', text: 'Hobbies & Interests – What do you like to do in your free time? (Dɛn na wopɛ sɛ woyɛ wɔ wo bere a w\'anya fa no mu?)' },
];
